# Generated by Django 3.2.9 on 2022-01-25 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=250, verbose_name='categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=250, null=True, verbose_name='cedula_vendedor')),
                ('cedula_cliente', models.CharField(max_length=250, null=True, verbose_name='correo_vendedor')),
                ('direccion_cliente', models.CharField(max_length=250, null=True, verbose_name='direccion_cliente')),
                ('ciudad_cliente', models.CharField(max_length=250, null=True, verbose_name='ciudad_cliente')),
                ('correo_cliente', models.CharField(max_length=250, null=True, verbose_name='correo_cliente')),
                ('telefono_cliente', models.CharField(max_length=250, null=True, verbose_name='telefono_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id_auto', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_factura', models.IntegerField(null=True, verbose_name='id_factura')),
                ('fecha_despacho', models.CharField(max_length=50, null=True)),
                ('fecha_pago', models.CharField(max_length=50, null=True)),
                ('pagada', models.BooleanField(null=True, verbose_name='pagada')),
                ('cantidad_1', models.IntegerField(null=True, verbose_name='cantidad_1')),
                ('precio_1', models.BigIntegerField(null=True, verbose_name='precio_1')),
                ('disponible_1', models.BooleanField(null=True, verbose_name='disponible_1')),
                ('nota_1', models.CharField(max_length=500, null=True, verbose_name='nota_1')),
                ('cantidad_2', models.IntegerField(null=True, verbose_name='cantidad_2')),
                ('precio_2', models.BigIntegerField(null=True, verbose_name='precio_2')),
                ('disponible_2', models.BooleanField(null=True, verbose_name='disponible_2')),
                ('nota_2', models.CharField(max_length=500, null=True, verbose_name='nota_2')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=255, verbose_name='nombre_producto')),
                ('inc_tela', models.BooleanField(null=True, verbose_name='inc_tela')),
                ('metros_tela', models.IntegerField(null=True, verbose_name='metros_tela')),
                ('tablado', models.BooleanField(null=True, verbose_name='inc_tablado')),
                ('costo', models.BigIntegerField(default=0, verbose_name='costo')),
                ('tiempo_entrega', models.IntegerField(null=True, verbose_name='tiempo_entrega')),
                ('nota', models.CharField(max_length=255, null=True, verbose_name='nota')),
                ('id_categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=205, verbose_name='nombre_proveedor')),
                ('telefono_proveedor', models.CharField(max_length=255, verbose_name='telefono_proveedor')),
                ('segundo_telefono', models.CharField(default=None, max_length=255, verbose_name='telefono_proveedor')),
                ('direccion_proveedor', models.CharField(max_length=255, verbose_name='direccion_proveedor')),
                ('observacion', models.CharField(default=None, max_length=500, verbose_name='observacion')),
            ],
        ),
        migrations.CreateModel(
            name='Transportadores',
            fields=[
                ('id_transportador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_transportador', models.CharField(max_length=250, null=True, verbose_name='nombre_transportador')),
                ('telefono_tranportador', models.CharField(max_length=250, null=True, verbose_name='telefono_tranportador')),
                ('cedula_transportador', models.CharField(max_length=250, null=True, verbose_name='cedula_transportador')),
                ('direccion_transportador', models.CharField(max_length=250, null=True, verbose_name='direccion_transportador')),
                ('nombre_contacto_emergencia', models.CharField(max_length=250, null=True, verbose_name='nombre_contacto_emergencia')),
                ('numero_contacto_emergencia', models.CharField(max_length=250, null=True, verbose_name='numero_contacto_emergencia')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id_vendedor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_vendedor', models.CharField(max_length=250, null=True, verbose_name='nombre_vendedor')),
                ('telefono_vendedor', models.CharField(max_length=250, null=True, verbose_name='telefono_vendedor')),
                ('cedula_vendedor', models.CharField(max_length=250, null=True, verbose_name='cedula_vendedor')),
                ('correo_vendedor', models.CharField(max_length=250, null=True, verbose_name='correo_vendedor')),
                ('direccion_vendedor', models.CharField(max_length=250, null=True, verbose_name='direccion_vendedor')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('nombre_contacto_emergencia', models.CharField(max_length=250, null=True, verbose_name='nombre_contacto_emergencia')),
                ('numero_contacto_emergencia', models.CharField(max_length=250, null=True, verbose_name='numero_contacto_emergencia')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_auto', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_venta', models.IntegerField(null=True, verbose_name='id_venta')),
                ('fecha_venta', models.CharField(max_length=250, null=True, verbose_name='telefono_vendedor')),
                ('fecha_entrega', models.CharField(max_length=250, null=True, verbose_name='numero_contacto_emergencia')),
                ('entregado', models.BooleanField(null=True, verbose_name='numero_contacto_emergencia')),
                ('valor_venta', models.BigIntegerField(null=True, verbose_name='valor_venta')),
                ('abono', models.BigIntegerField(null=True, verbose_name='abono')),
                ('saldo', models.BigIntegerField(null=True, verbose_name='saldo')),
                ('id_cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.clientes')),
                ('id_vendedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.vendedores')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.BigIntegerField(null=True, verbose_name='valor')),
                ('disponible', models.BooleanField(null=True, verbose_name='disponible')),
                ('nota', models.CharField(max_length=255, null=True, verbose_name='nota')),
                ('id_categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.categorias')),
                ('id_factura', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.facturas')),
                ('id_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('id_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaAlmacen',
            fields=[
                ('id_salida', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.CharField(max_length=255, null=True, verbose_name='fecha_remision')),
                ('destino', models.CharField(max_length=255, null=True, verbose_name='nombre_cliente')),
                ('id_stock1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_salidas_1', to='inventario.stock')),
                ('id_stock2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stock_salidas_2', to='inventario.stock')),
                ('transportador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.transportadores')),
            ],
        ),
        migrations.CreateModel(
            name='Remisiones',
            fields=[
                ('id_autogenerado', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_remision', models.IntegerField(null=True, verbose_name='id_remision')),
                ('prod1', models.CharField(max_length=400, null=True, verbose_name='prod1')),
                ('prod2', models.CharField(max_length=400, null=True, verbose_name='prod2')),
                ('fecha_remision', models.CharField(max_length=255, null=True, verbose_name='fecha_remision')),
                ('nombre_cliente', models.CharField(max_length=255, null=True, verbose_name='nombre_cliente')),
                ('id_transportador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.transportadores')),
                ('id_venta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='id_proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores'),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_auto', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_orden_pedido', models.IntegerField(null=True, verbose_name='id_orden_pedido')),
                ('tela', models.CharField(max_length=250, null=True, verbose_name='tela')),
                ('fecha', models.CharField(max_length=250, null=True, verbose_name='fecha')),
                ('fecha_despacho', models.CharField(max_length=250, null=True, verbose_name='fecha_despacho')),
                ('enviada', models.BooleanField(null=True, verbose_name='enviada')),
                ('recibida', models.BooleanField(null=True, verbose_name='recibida')),
                ('id_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
                ('id_vendedor', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='inventario.vendedores')),
                ('id_venta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='OtrosIngresosMercancia',
            fields=[
                ('id_ingreso_mercancia', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.CharField(max_length=50, null=True)),
                ('fecha_pago', models.CharField(max_length=50, null=True)),
                ('pagada', models.BooleanField(null=True, verbose_name='pagada')),
                ('cantidad_1', models.IntegerField(null=True, verbose_name='cantidad_1')),
                ('precio_1', models.BigIntegerField(null=True, verbose_name='precio_1')),
                ('disponible_1', models.BooleanField(null=True, verbose_name='disponible_1')),
                ('nota_1', models.CharField(max_length=500, null=True, verbose_name='nota_1')),
                ('cantidad_2', models.IntegerField(null=True, verbose_name='cantidad_2')),
                ('precio_2', models.BigIntegerField(null=True, verbose_name='precio_2')),
                ('disponible_2', models.BooleanField(null=True, verbose_name='disponible_2')),
                ('nota_2', models.CharField(max_length=500, null=True, verbose_name='nota_2')),
                ('id_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
                ('producto_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='producto_otros_1', to='inventario.productos')),
                ('producto_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='producto_otros_2', to='inventario.productos')),
            ],
        ),
        migrations.AddField(
            model_name='facturas',
            name='id_proveedor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='producto_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='producto_1', to='inventario.productos'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='producto_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='producto_2', to='inventario.productos'),
        ),
        migrations.CreateModel(
            name='EntregadosStock',
            fields=[
                ('id_entregado_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.BigIntegerField(null=True, verbose_name='valor')),
                ('disponible', models.BooleanField(null=True, verbose_name='disponible')),
                ('nota', models.CharField(max_length=255, null=True, verbose_name='nota')),
                ('id_categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.categorias')),
                ('id_factura', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.facturas')),
                ('id_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
                ('id_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
            ],
        ),
    ]
