# Generated by Django 3.2.9 on 2022-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=100, null=True, verbose_name='banco')),
                ('concepto', models.CharField(max_length=500, null=True, verbose_name='concepto')),
                ('fecha', models.CharField(max_length=50, null=True, verbose_name='fecha')),
                ('tipo', models.CharField(max_length=50, null=True, verbose_name='tipo')),
                ('valor', models.BigIntegerField(null=True, verbose_name='valor')),
            ],
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50, null=True, verbose_name='fecha')),
                ('concepto', models.CharField(max_length=500, null=True, verbose_name='concepto')),
                ('tipo', models.CharField(max_length=50, null=True, verbose_name='tipo')),
                ('valor', models.BigIntegerField(null=True, verbose_name='valor')),
            ],
        ),
    ]
