# Generated by Django 3.2.9 on 2022-02-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_bancos_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='valor_total',
            field=models.IntegerField(null=True, verbose_name='valor_total'),
        ),
    ]
