# Generated by Django 3.2.9 on 2022-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_pedidos_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='valor_total',
            field=models.BigIntegerField(null=True, verbose_name='valor_total'),
        ),
    ]
