# Generated by Django 3.2.9 on 2022-03-09 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_pedidos_enviada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidaalmacen',
            name='id_stock1',
        ),
        migrations.RemoveField(
            model_name='salidaalmacen',
            name='id_stock2',
        ),
        migrations.RemoveField(
            model_name='salidaalmacen',
            name='transportador',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='cantidad_1',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='cantidad_2',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='disponible_1',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='disponible_2',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='nota_1',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='nota_2',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='precio_1',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='precio_2',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='producto_1',
        ),
        migrations.RemoveField(
            model_name='facturas',
            name='producto_2',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id_proveedor',
        ),
        migrations.DeleteModel(
            name='OtrosIngresosMercancia',
        ),
        migrations.DeleteModel(
            name='SalidaAlmacen',
        ),
    ]
