# Generated by Django 3.2.9 on 2022-03-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20220309_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='id_factura',
        ),
    ]
