# Generated by Django 3.2.9 on 2022-03-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_facturas_id_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id_factura',
            field=models.IntegerField(null=True, verbose_name='id_factura'),
        ),
    ]
