# Generated by Django 3.2.9 on 2022-03-09 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_stock_id_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='id_factura',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.facturas'),
        ),
    ]
