# Generated by Django 3.2.9 on 2022-03-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_alter_stock_id_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remisiones',
            name='prod1',
        ),
        migrations.RemoveField(
            model_name='remisiones',
            name='prod2',
        ),
        migrations.AddField(
            model_name='remisiones',
            name='productos_entregados',
            field=models.CharField(max_length=2500, null=True, verbose_name='productos_entregados'),
        ),
    ]
