# Generated by Django 3.2.9 on 2022-07-09 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20220709_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='inc_tela',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='metros_tela',
        ),
    ]
