# Generated by Django 3.2.9 on 2022-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20220709_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(default=None, max_length=255, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='productos',
            name='nombre_proveedor',
            field=models.CharField(default=None, max_length=255, verbose_name='nombre_proveedor'),
        ),
    ]
