# Generated by Django 3.2.9 on 2022-07-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_facturas_nombre_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='nota',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
