# Generated by Django 3.2.9 on 2022-07-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_facturas_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='valor',
            field=models.BigIntegerField(default=0, verbose_name='valor'),
        ),
    ]
