# Generated by Django 3.2.9 on 2022-09-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_auto_20220709_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='cedula_cliente',
            field=models.CharField(max_length=250, null=True, verbose_name='cedula_cliente'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='nombre_cliente',
            field=models.CharField(max_length=250, null=True, verbose_name='nombre_cliente'),
        ),
    ]
