# Generated by Django 3.2.9 on 2022-09-22 17:19

from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_auto_20220922_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='nombre_vendedor',
            field=models.CharField(default=None, max_length=250, verbose_name=inventario.models.Vendedores),
        ),
    ]
