# Generated by Django 3.2.9 on 2022-09-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_ventas_nombre_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remisiones',
            name='nombre_cliente',
        ),
    ]
