# Generated by Django 3.2.9 on 2022-09-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_remove_remisiones_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiones',
            name='nota',
            field=models.CharField(max_length=2000, null=True, verbose_name='nota'),
        ),
    ]
