# Generated by Django 3.2.9 on 2022-09-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_remisiones_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='remisiones',
            name='nombre_transportador',
            field=models.CharField(max_length=250, null=True, verbose_name='nombre_transportador'),
        ),
    ]
