# Generated by Django 3.2.9 on 2022-09-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_remisiones_nombre_transportador'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='nombre_categoria',
            field=models.CharField(max_length=255, null=True, verbose_name='nombre_categoria'),
        ),
    ]
