# Generated by Django 3.2.9 on 2022-10-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0026_auto_20221024_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorEnCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorActual', models.BigIntegerField(null=True, verbose_name='valorActual')),
            ],
        ),
        migrations.RemoveField(
            model_name='caja',
            name='subTipo',
        ),
        migrations.AddField(
            model_name='caja',
            name='subtipo',
            field=models.CharField(max_length=50, null=True, verbose_name='subtipo'),
        ),
    ]
