# Generated by Django 3.2.9 on 2022-10-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_auto_20221024_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboDeCaja',
            fields=[
                ('id_auto', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_recibo_caja', models.IntegerField(null=True, verbose_name='numero_recibo_caja')),
                ('metodo_pago', models.CharField(max_length=50, null=True, verbose_name='metodo_pago')),
                ('saldo_cancelacion', models.CharField(max_length=50, null=True, verbose_name='saldo_cancelacion')),
                ('fecha', models.CharField(max_length=50, null=True, verbose_name='fecha')),
                ('id_venta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas')),
            ],
        ),
    ]
