# Generated by Django 3.2.9 on 2022-10-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0029_auto_20221025_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibodecaja',
            name='valor',
            field=models.BigIntegerField(null=True, verbose_name='valor'),
        ),
    ]
