# Generated by Django 3.2.9 on 2022-10-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0031_recibodecaja_id_movimiento_caja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibodecaja',
            old_name='id_movimiento_caja',
            new_name='id_movimiento',
        ),
    ]
