# Generated by Django 3.2.9 on 2022-10-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0032_rename_id_movimiento_caja_recibodecaja_id_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibodecaja',
            name='id_movimiento',
        ),
    ]
