# Generated by Django 3.2.9 on 2022-10-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0035_alter_recibodecaja_id_movimiento_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantesDeEgreso',
            fields=[
                ('id_auto', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_comprobante_egreso', models.IntegerField(null=True, verbose_name='numero_comprobante_egreso')),
                ('fecha', models.CharField(max_length=50, null=True, verbose_name='fecha')),
                ('metodo_pago', models.CharField(max_length=50, null=True, verbose_name='metodo_pago')),
                ('valor', models.BigIntegerField(null=True, verbose_name='valor')),
                ('facturas', models.CharField(max_length=500, null=True, verbose_name='facturas')),
                ('id_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.proveedores')),
            ],
        ),
    ]
