# Generated by Django 3.2.9 on 2022-11-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0037_comprobantesdeegreso_id_movimiento_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='abono',
            field=models.BigIntegerField(default=0, verbose_name='abono'),
        ),
    ]
